server {
	# listen port 443 with SSL/TLS
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name ${DOMAIN_NAME};

	# Certificate
	ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
	ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

	# Protocols TLS to subject
	ssl_protocols TLSv1.2 TLSv1.3;

	# root to file of site
	root /var/www/html;
	index index.php index.html index.hml;

	location / {
	try_files $uri $uri/ =404;
	}
}
