server {
	# listen port 443 with SSL/TLS
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name ${DOMAIN_NAME};

	# Certificate
	ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
	ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

	# Protocols TLS to subject
	ssl_protocols TLSv1.2 TLSv1.3;

	# root to file of site
	root /var/www/html;
	index index.php index.html index.hml;

	# Internal DNS server of Docker
	resolver 127.0.0.11 valid=30s;

	# writting to pattern of wordpress
	location / {
	try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		try_files $uri =404;

		# upstream_wordpress to handle the DNS of wordpress only someone acess the site
		set $upstream_wordpress wordpress:${WP_PORT};

		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass $upstream_wordpress;
		fastcgi_index index.php;

		# fastcgi params
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

	# block the hidden files
	location ~ /\.ht {
		deny all;
	}
}
