# version: '3.8'

services:

  ngnix:
    build: requirements/nginx
    image: ngnix:inception
    container_name: nginx
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      .env
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - ${VOLUME_WORDPRESS}:/var/www/html

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_name
      - db_user
      - db_password
      - db_root_password
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - ${VOLUME_MARIADB}:/var/lib/mysql

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_pass
      - wp_user
      - wp_user_pass
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - ${VOLUME_WORDPRESS}:/var/www/html

secrets:
  db_name:
    file: ../secrets/db_name
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  db_user:
    file: ../secrets/db_user
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  wp_user:
    file: ../secrets/wp_user
  wp_user_pass:
    file: ../secrets/wp_user_pass

networks:
  inception_network:
    driver: bridge
