# version: '3.8'

services:

  ngnix:
    build: requirements/nginx
    image: ngnix:inception
    container_name: nginx
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      .env
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    build: requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_name
      - db_user
      - db_password
      - db_root_password
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_pass
      - wp_user
      - wp_user_pass
      - redis_password
    networks:
      - inception_network
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build: requirements/bonus/redis
    image: redis:inception
    container_name: redis
    env_file:
      - .env
    secrets:
      - redis_password
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - inception_network

  ftp:
    build: requirements/bonus/ftp
    image: ftp/inception
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    env_file:
      - .env
    secrets:
      - ftp_user
      - ftp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  adminer:
    build: requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception_network

  static:
    build: requirements/bonus/static
    image: static:inception
    container_name: static
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception_network

  portainer:
    build: requirements/bonus/portainer
    image: portainer:inception
    container_name: portainer
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - portainer_user
      - portainer_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_network

secrets:
  db_name:
    file: ../secrets/db_name
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  db_user:
    file: ../secrets/db_user
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  wp_user:
    file: ../secrets/wp_user
  wp_user_pass:
    file: ../secrets/wp_user_pass

  redis_password:
    file: ../secrets/redis_password

  ftp_user:
    file: ../secrets/ftp_user
  ftp_password:
    file: ../secrets/ftp_password

  portainer_user:
    file: ../secrets/portainer_user
  portainer_password:
    file: ../secrets/portainer_password

volumes:
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_WORDPRESS}
  mariadb_data:
    name: maria
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MARIADB}
  redis_data:
    name: redis
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_REDIS}
  portainer_data:
    name: portainer
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PORTAINER}

networks:
  inception_network:
    driver: bridge
